FROM centos:7.2.1511
RUN  yum -y install epel-release && yum -y install golang
RUN yum -y install wget && wget https://github.com/ethereum/go-ethereum/archive/v1.8.27.tar.gz && tar -zxvf v1.8.27.tar.gz
RUN rpm --rebuilddb && yum -y install gcc automake autoconf libtool make && yum -y install gcc gcc-c++
WORKDIR go-ethereum-1.8.27
RUN  make all
COPY ./conf/start-ethereum.sh build/bin/
COPY ./conf/genesis.json build/bin/
WORKDIR build/bin
RUN mkdir chain && ./geth --datadir chain  --rpc   --rpccorsdomain "*" init genesis.json
CMD ["./start-ethereum.sh"]
