FROM centos:7.6.1810
RUN  yum -y install epel-release && yum -y update && yum -y install redis
COPY ./conf/redis.conf /etc/redis.conf
COPY ./conf/start-redis.sh .
RUN chmod -R 777 start-redis.sh
ENTRYPOINT ["/usr/sbin/init"]





