database:
  redis:
    address: 47.100.205.196
    port: 6379
    histroy-path: /root/docker/redis/root/.rediscli_history
    download-path: /root/docker/redis/root/.rediscli_history
    command-file-path: /root/docker/redis/root/.rediscli_history
    exclude-words: exit,auth
ethereum-config:
  ethereum-url: http://47.100.205.196:8545
  ethereum-admin-account: '{"address":"4e0dc4ffa4609989c00183bc4a78b5ea70c33494","crypto":{"cipher":"aes-128-ctr","ciphertext":"ab3eaddba953c02861e539ed93f5c28945267c3435b63c2531bb669f2ebd96cc","cipherparams":{"iv":"d271f17fbd59f57d1de068702b3817e4"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"400aacf467e873f9232418231abcc535934bb027db758fd637ff0739ff6a84f6"},"mac":"00fb7135ce6dbfef42676b786f2459ce894040b686101a35ea726d5ee2780e76"},"id":"064efa43-f6d2-4673-8c27-c56d197695b2","version":3}'
  ethereum-admin-address: 0x4e0dc4ffa4609989c00183bc4a78b5ea70c33494
  ethereum-admin-password: abc
  ethereum-contract-address: 0xd929c03b3c2d4be4e6ad0e542938947aff658f46
ipfs:
  execute-command: docker exec ipfs
  host-upload-path: /root/docker/ipfs/upload/.rediscli_history
  docker-upload-path: /upload/.rediscli_history

