database:
  redis:
    address: localhost
    port: 6379
    aofPath: /root/docker/redis/root/.rediscli_history
    downloadPath: /root/docker/redis/root/.rediscli_history
    commandFilePath: /root/docker/redis/root/.rediscli_history
ethereum:
  address: localhost
  port: 8545
